# ansible/11-ferramentas-cluster/tasks/01-instalacao.yml
---
- name: Verificar se o executável do Etcd já está instalado na VM
  ansible.builtin.stat:
    path: "/usr/local/bin/etcdctl"
  register: etcdctl_bin

- name: Instalar o Etcd se não existir
  when: not etcdctl_bin.stat.exists
  block:
    - name: Copiar Etcd para a VM (em /tmp)
      ansible.builtin.copy:
        src: "{{ pasta_temporarios }}/etcd-bin.tar.gz"
        dest: "/tmp/etcd-bin.tar.gz"
        mode: "0644"

    - name: Descompactar Etcd em /usr/local/bin
      ansible.builtin.unarchive:
        src: "/tmp/etcd-bin.tar.gz"
        dest: "/tmp"
        remote_src: true
        mode: "0755"

    - name: Instalar binários do Etcd
      ansible.builtin.copy:
        src: "/tmp/etcd-{{ versao_etcd }}-linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
        remote_src: true
      become: true
      loop:
        - etcdctl

  always:
    - name: Remover diretório temporário do Etcd
      ansible.builtin.file:
        path: "/tmp/etcd-{{ versao_etcd }}-linux-amd64"
        state: absent

    - name: Remover arquivo temporário do Etcd
      ansible.builtin.file:
        path: "/tmp/etcd-bin.tar.gz"
        state: absent

- name: Verificar se o executável do kubectl já está instalado na VM
  ansible.builtin.stat:
    path: "/usr/local/bin/kubectl"
  register: kubectl_bin

- name: Instalar o kubectl se não existir
  when: not kubectl_bin.stat.exists
  block:
    - name: Copiar kubectl para a VM
      ansible.builtin.copy:
        src: "{{ pasta_temporarios }}/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: "0755"
      become: true

    - name: Criar diretório ~/.kube para usuário padrão do vagrant
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Criar diretório de PKIs para as ferramentas
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube/pki"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"
