# ansible/13-configuracoes-cluster/tasks/07-metallb.yml
---
- name: Adicionar repositório helm do MetalLB
  ansible.builtin.command:
    cmd: "helm repo add metallb https://metallb.github.io/metallb"
  register: resultado_repo_add
  changed_when: "'already exists' not in resultado_repo_add.stdout"

- name: Atualizar repositórios helm
  ansible.builtin.command:
    cmd: "helm repo update"
  changed_when: false

- name: Garantir diretório charts na home do usuário do ansible
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/charts"
    state: directory
    mode: "0755"

- name: Criar arquivo de configuração Helm para o MetalLB
  ansible.builtin.template:
    src: metallb-helm-config.yml.j2
    dest: "/home/{{ ansible_user }}/charts/metallb-helm-config.yml"
    mode: "0644"

- name: Criar manifesto de namespace e PodSecurity para o MetalLB
  ansible.builtin.template:
    src: metallb-namespace.yml.j2
    dest: "/home/{{ ansible_user }}/charts/metallb-namespace.yml"
    mode: "0644"

- name: Aplicar manifesto do namespace MetalLB
  ansible.builtin.command:
    cmd: "kubectl apply -f /home/{{ ansible_user }}/charts/metallb-namespace.yml"
  register: resultado_ns
  changed_when: "'configured' in resultado_ns.stdout or 'created' in resultado_ns.stdout"

- name: Instalar chart do MetalLB
  ansible.builtin.command:
    cmd: >
      helm upgrade --install metallb metallb/metallb
      --namespace metallb
      --values /home/{{ ansible_user }}/charts/metallb-helm-config.yml
      --atomic --wait --timeout 120s
  register: resultado_helm_upgrade
  changed_when: "'installed' in resultado_helm_upgrade.stdout or 'upgraded' in resultado_helm_upgrade.stdout"

- name: Criar manifesto de configuração do Advertisement e do IP Pool do MetalLB
  ansible.builtin.template:
    src: metallb-adv-pool.yml.j2
    dest: "/home/{{ ansible_user }}/charts/metallb-adv-pool.yml"
    mode: "0644"

- name: Aplicar manifesto do Advertisement/IP Pool
  ansible.builtin.command:
    cmd: "kubectl apply -f /home/{{ ansible_user }}/charts/metallb-adv-pool.yml"
  register: resultado_adv
  changed_when: "'configured' in resultado_adv.stdout or 'created' in resultado_adv.stdout"