# ansible/09-kubelet/tasks/01-instalacao-containerd.yml
---
- name: Adicionar repositório Docker
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Instalar containerd
  ansible.builtin.dnf:
    name: containerd.io
    state: present

- name: Garantir diretório /etc/containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"
