# ansible/09-kubelet/tasks/03-instalacao-plugins-cni.yml
---
- name: Criar diretórios necessários para os plugins do CNI
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/cni/bin
    - /etc/cni/net.d

- name: Verificar se os plugins do CNI já estão instalados
  ansible.builtin.stat:
    path: "/opt/cni/bin/loopback"
  register: cni_bin

- block:
  - name: Copiar compactado dos plugins para a VM
    ansible.builtin.copy:
      src: "{{ pasta_temporarios }}/cni-plugins.tgz"
      dest: "/tmp/cni-plugins.tgz"
      mode: "0644"

  - name: Descompactar plugins diretamente em /opt/cni/bin
    ansible.builtin.unarchive:
      src: "/tmp/cni-plugins.tgz"
      dest: "/opt/cni/bin"
      remote_src: true
      mode: "0755"

  always:
    - name: Remover arquivo compactado dos plugins
      ansible.builtin.file:
        path: "/tmp/cni-plugins.tgz"
        state: absent
  when: not cni_bin.stat.exists