# ansible/09-kubelet/tasks/main.yml
---
- ansible.builtin.include_tasks: 01-instalacao-containerd.yml

- ansible.builtin.include_tasks: 02-instalacao-kubelet.yml

- ansible.builtin.include_tasks: 03-pki.yml

- ansible.builtin.include_tasks: 04-configuracao.yml