# ansible/01-pki/tasks/01-setup.yml
---
- name: Remover estrutura anterior de outras gerações no caso de regerar os certificados
  ansible.builtin.file:
    path: "{{ pki_pasta_base }}"
    state: absent
  when: pki_regerar_certs | bool

- name: Criar estrutura de diretórios para certificados
  ansible.builtin.file:
    path: "{{ pasta }}"
    state: directory
    mode: "0755"
  loop: "{{ pki_pastas.values() | list }}"
  loop_control:
    loop_var: pasta
    label: "{{ pasta | relpath(playbook_dir) }}"
