# ansible/01-pki/tasks/01-setup.yml
---
- name: Remover estrutura anterior de outras gerações no caso de regerar os certificados
  ansible.builtin.file:
    path: "{{ pki_pasta_base }}"
    state: absent
  when: pki_regerar_certs | bool

- name: Criar estrutura de diretórios para certificados
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    recurse: true
  loop: "{{ pki_pastas.values() | list }}"
