# ansible/01-pki/tasks/02-root-ca.yml
---
- name: Verificar arquivos existentes do Root CA
  ansible.builtin.stat:
    path: "{{ arquivo }}"
  loop:
    - "{{ pki_root_ca.path_chave }}"
    - "{{ pki_root_ca.path_cert }}"
  loop_control:
    loop_var: arquivo
    label: "{{ arquivo | relpath(pasta_artefatos) }}"
  register: ca_root_arquivos
  delegate_to: localhost

- name: Criar chave privada do Root CA
  community.crypto.openssl_privatekey:
    path: "{{ pki_root_ca.path_chave }}"
    type: "{{ pki_cifra_tipo }}"
    curve: "{{ pki_cifra_algo }}"
    state: "present"
    force: true
  when: not ca_root_arquivos.results[0].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost

- name: Gerar CSR do Root CA
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ pki_root_ca.path_chave }}"
    digest: "{{ pki_algoritmo_hash }}"
    subject:
      C: BR
      ST: Minas Gerais
      L: Uberlandia
      O: K8s-in-a-Box
      OU: Autoridade Raiz
      CN: K8s-in-a-Box Root CA
    use_common_name_for_san: false
    basic_constraints:
      - "CA:TRUE"
      - "pathlen:1"
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
  when: not ca_root_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost
  register: ca_root_csr

- name: Criar certificado auto-assinado do Root CA
  community.crypto.x509_certificate:
    path: "{{ pki_root_ca.path_cert }}"
    csr_content: "{{ ca_root_csr.csr }}"
    privatekey_path: "{{ pki_root_ca.path_chave }}"
    provider: selfsigned
    selfsigned_digest: "{{ pki_algoritmo_hash }}"
    selfsigned_not_after: "+{{ pki_validade.root | default(1825) }}d"
    mode: "0644"
    force: true
  when: not ca_root_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost
