# ansible/01-pki/tasks/14-cert-admin-account.yml
---
- name: Verificar arquivos existentes da chave para o Admin Account
  ansible.builtin.stat:
    path: "{{ arquivo }}"
  loop:
    - "{{ pki_certs.admin_account.path_chave }}"
    - "{{ pki_certs.admin_account.path_csr }}"
    - "{{ pki_certs.admin_account.path_cert }}"
  loop_control:
    loop_var: arquivo
    label: "{{ arquivo }}"
  register: admin_account_arquivos
  delegate_to: localhost

- name: Criar chave privada do certificado para o Admin Account
  community.crypto.openssl_privatekey:
    path: "{{ pki_certs.admin_account.path_chave }}"
    type: "{{ pki_cifra_tipo }}"
    curve: "{{ pki_cifra_algo }}"
    state: "present"
    force: true
  when: not admin_account_arquivos.results[0].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost

- name: Gerar CSR do certificado para o Admin Account
  community.crypto.openssl_csr:
    path: "{{ pki_certs.admin_account.path_csr }}"
    privatekey_path: "{{ pki_certs.admin_account.path_chave }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    subject: "{{ pki_subject_padrao 
      | combine({
        'O': 'system:masters',
        'OU': 'Administração do Kubernetes',
        'CN': 'kubernetes-admin'
      })
    }}"
    use_common_name_for_san: false
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: true
    force: true
  when: not admin_account_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost

- name: Assinar certificado para o Admin Account com o respectivo CA intermediário
  community.crypto.x509_certificate:
    path: "{{ pki_certs.admin_account.path_cert }}"
    csr_path: "{{ pki_certs.admin_account.path_csr }}"
    provider: ownca
    ownca_path: "{{ pki_certs.admin_account.ca_pai.path_cert }}"
    ownca_privatekey_path: "{{ pki_certs.admin_account.ca_pai.path_chave }}"
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_not_after: "+{{ pki_validade.certificado | default(30) }}d"
    mode: "0644"
    force: true
  when: not admin_account_arquivos.results[2].stat.exists or (pki_regerar_certs | default(false) | bool)
  delegate_to: localhost
