# ansible/01-pki/tasks/main.yml
---
- ansible.builtin.include_tasks: 01-setup.yml
  tags:
    - pki
    - pki:setup
    - pki:dirs

- ansible.builtin.include_tasks: 02-root-ca.yml
  tags:
    - pki
    - pki:ca
    - pki:root
    - pki:root:ca

- ansible.builtin.include_tasks: 03-ca-etcd.yml
  tags:
    - pki
    - pki:ca
    - pki:etcd
    - pki:etcd:ca

- ansible.builtin.include_tasks: 04-ca-kubernetes.yml
  tags:
    - pki
    - pki:ca
    - pki:kubernetes
    - pki:kubernetes:ca

- ansible.builtin.include_tasks: 05-cert-etcd-apiserver-cli.yml
  tags:
    - pki
    - pki:cert
    - pki:etcd
    - pki:etcd:apiserver

- ansible.builtin.include_tasks: 06-cert-etcd-server.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:cert
    - pki:etcd
    - pki:etcd:server

- ansible.builtin.include_tasks: 07-cert-etcd-peer.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:cert
    - pki:etcd
    - pki:etcd:peer

- ansible.builtin.include_tasks: 08-cert-kube-apiserver.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:cert
    - pki:k8s
    - pki:k8s:apiserver

- ansible.builtin.include_tasks: 09-cert-kube-controller-manager.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:cert
    - pki:k8s
    - pki:k8s:controller-manager

- ansible.builtin.include_tasks: 10-cert-kube-scheduler.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:cert
    - pki:k8s
    - pki:k8s:scheduler