# ansible/01-pki/tasks/main.yml
---
- ansible.builtin.include_tasks: 01-setup.yml

- ansible.builtin.include_tasks: 02-root-ca.yml

- ansible.builtin.include_tasks: 03-ca-etcd.yml

- ansible.builtin.include_tasks: 04-ca-kubernetes.yml

- ansible.builtin.include_tasks: 05-cert-etcd-server.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 06-cert-etcd-peer.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 07-cert-kube-apiserver.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 08-cert-kube-apiserver-etcd-cli.yml

- ansible.builtin.include_tasks: 09-cert-kube-apiserver-kubelet-cli.yml

- ansible.builtin.include_tasks: 10-cert-kube-controller-manager.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 11-cert-kube-scheduler.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 12-cert-kubelet.yml
  loop: "{{ groups['k8s_nodes'] }}"
  loop_control:
    loop_var: node_host

- ansible.builtin.include_tasks: 13-cert-kube-proxy.yml
  loop: "{{ groups['k8s_nodes'] }}"
  loop_control:
    loop_var: node_host

- ansible.builtin.include_tasks: 14-cert-service-account.yml

- ansible.builtin.include_tasks: 15-cert-admin-account.yml