# ansible/01-pki/tasks/main.yml
---
- ansible.builtin.include_tasks: 01-setup.yml

- ansible.builtin.include_tasks: 101-root-ca.yml

- ansible.builtin.include_tasks: 102-ca-etcd.yml

- ansible.builtin.include_tasks: 103-ca-kubernetes.yml

- ansible.builtin.include_tasks: 104-ca-front-proxy.yml

- ansible.builtin.include_tasks: 201-cert-etcd-server.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 202-cert-etcd-peer.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 203-cert-etcd-cli.yml

- ansible.builtin.include_tasks: 211-cert-kube-apiserver.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 212-cert-kube-apiserver-etcd-cli.yml

- ansible.builtin.include_tasks: 213-cert-kube-apiserver-kubelet-cli.yml

- ansible.builtin.include_tasks: 214-cert-kube-controller-manager.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 215-cert-kube-scheduler.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host

- ansible.builtin.include_tasks: 221-cert-kubelet.yml
  loop: "{{ groups['k8s_nodes'] }}"
  loop_control:
    loop_var: node_host

- ansible.builtin.include_tasks: 222-cert-kube-proxy.yml
  loop: "{{ groups['k8s_nodes'] }}"
  loop_control:
    loop_var: node_host

- ansible.builtin.include_tasks: 223-cert-service-account.yml

- ansible.builtin.include_tasks: 224-cert-admin-account.yml

- ansible.builtin.include_tasks: 231-cert-front-proxy-cli.yml