# ansible/09-kube-controller-manager-pod/handlers/main.yml
---
- name: Reiniciar Static Pod do kube-controller-manager
  ansible.builtin.file:
    path: /etc/kubernetes/manifests/kube-controller-manager.yaml
    state: touch
    modification_time: now
    owner: root
    group: root
    mode: "0644"
