# ansible/03-balanceador/tasks/02-configuracao-haproxy.yml
---
- name: Verificar sintaxe do template HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /tmp/haproxy.cfg.check
    mode: '0644'
    validate: 'haproxy -c -f %s'
  check_mode: true
  changed_when: false

- name: Criar configuração do HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: root
    group: root
    validate: 'haproxy -c -f %s'
    backup: true

- name: Habilitar HAProxy no boot
  ansible.builtin.systemd:
    name: haproxy
    enabled: true

- name: Garantir que HAProxy está rodando
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: restarted
