# ansible/08-kube-apiserver-pod/tasks/main.yml
---
- name: Garantir estrutura de diretórios do kube-apiserver
  ansible.builtin.include_tasks: 01-instalacao.yml

- name: Transferir os PKIs que o kube-apiserver precisa
  ansible.builtin.include_tasks: 02-pki.yml

- name: Efetuar criação dos arquivos de configuração
  ansible.builtin.include_tasks: 03-configuracao.yml
