# ansible/02-sistema/tasks/1-base.yml
---
- name: Colocar SELinux em modo permissivo (iremos tratar do SELinux no futuro)
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Garantir que chronyd está ativo
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

- name: Configurar makestep no chrony.conf (para problemas de sincronia com snapshots)
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^makestep'
    line: 'makestep 1.0 -1'
    state: present
  notify: Reiniciar chronyd

- name: Atualizar cache do dnf
  become: true
  ansible.builtin.dnf:
    update_cache: true

- name: Atualizar todos os pacotes  # noqa package-latest
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: atualiza_sistema == "todos"

- name: Atualizar apenas pacotes de segurança  # noqa package-latest
  become: true
  ansible.builtin.dnf:
    name: "*"
    security: true
    state: latest
  when: atualiza_sistema == "seguranca"

- name: Instalar pacotes extras necessários
  become: true
  ansible.builtin.dnf:
    name: "{{ pacotes_extras }}"
    state: present

- name: Verificar se precisa reiniciar
  ansible.builtin.command: needs-restarting -r
  register: reboot_check
  ignore_errors: true
  changed_when: reboot_check.rc == 1
  failed_when: reboot_check.rc not in [0, 1]

- name: Reiniciar se necessário
  ansible.builtin.reboot:
    post_reboot_delay: 10
    reboot_timeout: 300
  when: reboot_check.rc == 1

- name: Configurar o TZ para o especificado em defaults
  community.general.timezone:
    name: "{{ timezone_tz }}"

- name: Ler configuração atual do locale  # noqa no-changed-when
  ansible.builtin.command: localectl status
  register: resultado_locale
  changed_when: false

- name: Configurar locale se necessário
  ansible.builtin.command: "localectl set-locale LANG={{ locale_lang }}"
  when: "'LANG=' ~ locale_lang not in resultado_locale.stdout"
  changed_when: true

- name: Gerar arquivo /etc/hosts para cada nó do cluster
  ansible.builtin.template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Verificar se Tailspin já está instalado na VM
  ansible.builtin.stat:
    path: "/usr/local/bin/tspin"
  register: tailspin_bin

- name: Instalar Tailspin se não existir
  when: not tailspin_bin.stat.exists
  block:
    - name: Copiar Tailspin para a VM (em /tmp)
      ansible.builtin.copy:
        src: "{{ pasta_temporarios }}/tailspin.tar.gz"
        dest: "/tmp/tailspin.tar.gz"
        mode: "0644"

    - name: Descompactar Tailspin em /usr/local/bin
      ansible.builtin.unarchive:
        src: "/tmp/tailspin.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        owner: "root"
        group: "root"
        mode: "0755"
        creates: "/usr/local/bin/tspin"

  always:
    - name: Remover arquivo temporário do Tailspin
      ansible.builtin.file:
        path: "/tmp/tailspin.tar.gz"
        state: absent
