# ansible/02-sistema/tasks/1-base.yml
---
- name: Colocar SELinux em modo desabilitado (iremos tratar do SELinux no futuro)
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: disabled
  notify: Reboot Necessário

- name: Garantir que chronyd está ativo
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

- name: Configurar makestep no chrony.conf (para problemas de sincronia com snapshots)
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^makestep'
    line: 'makestep 1.0 -1'
    state: present
  notify: Reiniciar chronyd

- name: Atualizar cache do dnf
  become: true
  ansible.builtin.dnf:
    update_cache: true

- name: Instalar pacotes extras necessários
  become: true
  ansible.builtin.dnf:
    name: "{{ pacotes_extras }}"
    state: present

- name: Atualizar todos os pacotes
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: atualiza_sistema == "all"

- name: Atualizar apenas pacotes de segurança
  become: true
  ansible.builtin.dnf:
    name: "*"
    security: true
    state: latest
  when: atualiza_sistema == "patch"

- name: Verificar se precisa reiniciar
  ansible.builtin.command: needs-restarting -r
  register: reboot_check
  ignore_errors: true
  changed_when: reboot_check.rc == 1
  notify: Reboot Necessário

- name: Configurar o TZ para o especificado em defaults
  community.general.timezone:
    name: "{{ timezone_tz }}"

- name: Configurar locale do sistema para o especificado em defaults
  ansible.builtin.ini_file:
    path: /etc/locale.conf
    section: null
    option: LANG
    value: "{{ locale_lang }}"
    create: yes

- name: Gerar arquivo /etc/hosts para cada nó do cluster
  ansible.builtin.template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Verificar se Tailspin já está instalado na VM
  ansible.builtin.stat:
    path: "/usr/local/bin/tspin"
  register: tailspin_bin

- block:
    - name: Copiar Tailspin para a VM (em /tmp)
      ansible.builtin.copy:
        src: "{{ pasta_temporarios }}/tailspin.tar.gz"
        dest: "/tmp/tailspin.tar.gz"
        mode: "0644"

    - name: Descompactar Tailspin em /usr/local/bin
      ansible.builtin.unarchive:
        src: "/tmp/tailspin.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        owner: "root"
        group: "root"
        mode: "0755"
        creates: "/usr/local/bin/tspin"

  always:
    - name: Remover arquivo temporário do Tailspin
      ansible.builtin.file:
        path: "/tmp/tailspin.tar.gz"
        state: absent
  when: not tailspin_bin.stat.exists

