# ansible/addon-apps-cluster/tasks/main.yml
---
- name: Configurar Labels e Taints dos nós do cluster
  ansible.builtin.import_tasks: 01-labels-taints.yml

- name: Instalação e configuração do CoreDNS
  ansible.builtin.import_tasks: 02-coredns.yml

- name: Instalação e configuração do Metrics Server
  ansible.builtin.import_tasks: 03-metrics.yml

- name: Instalação e configuração do NFS Subdir External Provisioner
  ansible.builtin.import_tasks: 04-nfs-storage.yml

- name: Instalação e configuração do Headlamp Dashboard
  ansible.builtin.import_tasks: 05-headlamp.yml

- name: Instalação e configuração do Vertical Pod Autoscaler (VPA)
  ansible.builtin.import_tasks: 06-vpa.yml

- name: Instalação e configuração do Prometheus Operator e Grafana (Prometheus Stack)
  ansible.builtin.import_tasks: 07-prometheus-stack.yml
