# ansible/09-kube-controller-manager-pod/tasks/01-instalacao.yml
---
- name: Garantir diretório de configuração isolado do kube-controller-manager
  ansible.builtin.file:
    path: /etc/kubernetes/conf/kube-controller-manager
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Garantir diretório de manifestos do Kubernetes
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    owner: root
    group: root
    mode: "0755"
