# ansible/addon-kube-proxy/handlers/main.yml
---
- name: Reiniciar DaemonSet do kube-proxy
  ansible.builtin.command:
    cmd: "kubectl rollout restart daemonset/kube-proxy -n kube-system"
  changed_when: true
