apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador
  namespace: exemplos
  labels:
    app: contador-app
    componente: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contador-app
      componente: web
  template:
    metadata:
      labels:
        app: contador-app
        componente: web
    spec:
      serviceAccountName: exemplos-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: php
          image: php:8.5-apache
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: pagina
              mountPath: /var/www/html
            - name: dados
              mountPath: /dados
            - name: apache-config
              mountPath: /etc/apache2/ports.conf
              subPath: ports.conf
            - name: apache-config
              mountPath: /etc/apache2/sites-enabled/000-default.conf
              subPath: 000-default.conf
            - name: var-run
              mountPath: /var/run/apache2
            - name: var-lock
              mountPath: /var/lock/apache2
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pagina
          configMap:
            name: contador-pagina
        - name: dados
          persistentVolumeClaim:
            claimName: contador-pvc
        - name: apache-config
          configMap:
            name: contador-apache-config
        - name: var-run
          emptyDir: {}
        - name: var-lock
          emptyDir: {}
