# ansible/100-exemplos/files/vpa/01-vpa-initial-cronjob.yml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vpa-stress-cronjob
  namespace: exemplos
  labels:
    app: vpa-stress-cronjob
    componente: cronjob
spec:
  schedule: "5-55/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: vpa-stress-cronjob
        componente: cronjob
    spec:
      ttlSecondsAfterFinished: 1800
      template:
        metadata:
          labels:
            app: vpa-stress-cronjob
            componente: cronjob
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          restartPolicy: Never
          containers:
            - name: stress-container
              image: alpine:3.20
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "Iniciando estresse de CPU (VPA Initial) por 3 minutos..."
                  timeout 180s sh -c 'while true; do dd if=/dev/urandom bs=1M count=10 2>/dev/null | sha256sum | sha512sum | sha512sum > /dev/null; done'
                  echo "Estresse de CPU finalizado."
              resources:
                requests:
                  cpu: "10m"
                  memory: "32Mi"
                limits:
                  cpu: "1000m"
                  memory: "256Mi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-stress-cronjob-vpa
  namespace: exemplos
spec:
  targetRef:
    apiVersion: batch/v1
    kind: CronJob
    name: vpa-stress-cronjob
  updatePolicy:
    updateMode: "Initial"
