# ansible/00-artefatos/tasks/download-artefatos.yml
---
- name: Baixar artefatos necessários no host
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ pasta_temporarios }}/{{ item.value.arquivo }}"
    mode: "0644"
    force: false
    checksum: "{{ item.value.get('checksum', '') | ternary(item.value.get('checksum', ''), omit) }}"
  loop: "{{ download_artefatos | dict2items }}"
  when: >
    (metodo_instalacao | default('bin')) == 'bin' or
    item.key not in ['kube-apiserver-bin', 'kube-controller-manager-bin', 'kube-scheduler-bin']
  loop_control:
    label: "{{ item.key }}"
