# ansible/12-configuracoes-cluster/tasks/02-flannel.yml
---
- name: Verificar se namespace kube-flannel já existe
  ansible.builtin.command:
    cmd: "kubectl get ns kube-flannel"
  register: resultado_ns
  failed_when: false
  changed_when: false

- name: Instalar o Flannel se não estiver instalado
  when: resultado_ns.rc != 0
  block:
    - name: Garantir que namespace kube-flannel existe
      ansible.builtin.command:
        cmd: "kubectl create ns kube-flannel"
      changed_when: true

    - name: Aplicar label PodSecurity no namespace kube-flannel
      ansible.builtin.command:
        cmd: "kubectl label ns kube-flannel pod-security.kubernetes.io/enforce=privileged"
      changed_when: true

    - name: Adicionar repositório helm flannel
      ansible.builtin.command:
        cmd: "helm repo add flannel https://flannel-io.github.io/flannel/"
      changed_when: true

    - name: Atualizar repositórios helm
      ansible.builtin.command:
        cmd: "helm repo update"
      changed_when: false

    - name: Instalar chart do Flannel
      ansible.builtin.command:
        cmd: >
          helm install flannel flannel/flannel
          --namespace kube-flannel
          --set podCidr="{{ rede_cidr_pods }}"
      changed_when: true
