apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-hpa-teste-stress
  namespace: exemplos
  labels:
    app: hello-app
    componente: cronjob
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: hello-app
        componente: cronjob
    spec:
      ttlSecondsAfterFinished: 1800
      template:
        metadata:
          labels:
            app: hello-app
            componente: cronjob
        spec:
          serviceAccountName: exemplos-sa
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          restartPolicy: Never
          containers:
            - name: fortio
              image: fortio/fortio:1.73.2
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              args:
                - load
                - -n  # Ignora com -t, roda até timeout
                - "0"
                - -c
                - "250"      # +150 concurrent
                - -qps       # Rate máximo
                - "2000"    # 2k req/s
                - -t
                - "180s"     # 3min full blast
                - http://hello-svc
              resources:
                requests:
                  cpu: "10m"
                  memory: "32Mi"
                limits:
                  cpu: "1000m"
                  memory: "256Mi"
