# ansible/100-exemplos/files/hello/09-hello-vpa.yml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hello-app-vpa
  namespace: exemplos
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-app
  updatePolicy:
    updateMode: "Off" # Recomendações estatísticas apenas (para rodar junto com HPA)
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hello-stress-vpa
  namespace: exemplos
spec:
  targetRef:
    apiVersion: batch/v1
    kind: CronJob
    name: hello-hpa-teste-stress
  updatePolicy:
    updateMode: "Initial" # Altera limites apenas no início de cada execução (evita reinício do Job)
