# ansible/04-etcd/tasks/03-configuracao.yml
---
- name: Criar arquivo de configuração
  ansible.builtin.template:
    src: etcd.conf.yml.j2
    dest: /etc/etcd/etcd.conf.yml
    owner: etcd
    group: etcd
    mode: "0600"

- name: Criar arquivo de serviço systemd
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: "0644"

- name: Garantir serviço ativo
  ansible.builtin.systemd:
    name: etcd
    enabled: yes
    state: restarted
    daemon_reload: true