# ansible/playbook.yml
---
- name: Tarefas a serem executadas no host
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - role: 00-artefatos
      tags:
        - artefatos
        - cluster

- name: Criação local dos CAs e certificados do projeto
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - role: 01-pki
      tags:
        - pki
        - cluster

- name: Configurações base para todas as máquinas
  hosts:
    - todos
  become: true
  gather_facts: false
  roles:
    - role: 02-sistema
      tags:
        - sistema
        - cluster

- name: Configurações do Balanceador de carga
  hosts: loadbalancers
  become: true
  gather_facts: false
  roles:
    - role: 03-balanceador
      tags:
        - balanceador
        - cluster

- name: Configurações comuns a todos os nós
  hosts: k8s_nodes
  become: true
  gather_facts: false
  roles:
    - role: 04-kubernetes-base
      tags:
        - kubernetes-base
        - cluster

- name: Configurações do cluster Etcd
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 05-etcd
      tags:
        - etcd
        - cluster

- name: Configuração do kube-apiserver
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 06-kube-apiserver
      tags:
        - kube-apiserver
        - cluster

- name: Configuração do kube-controller-manager
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 07-kube-controller-manager
      tags:
        - kube-controller-manager
        - cluster

- name: Configuração do kube-scheduler
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 08-kube-scheduler
      tags:
        - kube-scheduler
        - cluster

- name: Configuração do kubelet
  hosts: k8s_nodes
  become: true
  gather_facts: false
  roles:
    - role: 09-kubelet
      tags:
        - kubelet
        - cluster

- name: Configuração do kube-proxy
  hosts: k8s_nodes
  become: true
  gather_facts: false
  roles:
    - role: 10-kube-proxy
      tags:
        - kube-proxy
        - cluster
