# ansible/cluster.yml
---
- name: Tarefas a serem executadas no host
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - role: 00-artefatos
      tags:
        - cluster-artefatos
        - cluster

- name: Criação local dos CAs e certificados do projeto
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - role: 01-pki
      tags:
        - cluster-pki
        - cluster

- name: Configurações base para todas as máquinas
  hosts:
    - todos
  become: true
  gather_facts: false
  roles:
    - role: 02-sistema
      tags:
        - cluster-sistema
        - cluster

- name: Configurações do Balanceador de carga
  hosts: loadbalancers
  become: true
  gather_facts: false
  roles:
    - role: 03-balanceador
      tags:
        - cluster-balanceador
        - cluster

- name: Configurações do NFS
  hosts: nfs
  become: true
  gather_facts: false
  roles:
    - role: 04-nfs
      tags:
        - cluster-nfs
        - cluster

- name: Configurações comuns a todos os nós
  hosts: cluster
  become: true
  gather_facts: false
  roles:
    - role: 05-cluster-base
      tags:
        - cluster-kubernetes-base
        - cluster

- name: Configurações do cluster Etcd
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 06-etcd
      tags:
        - cluster-etcd
        - cluster

- name: Configuração do kube-apiserver
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 07-kube-apiserver
      tags:
        - cluster-kube-apiserver
        - cluster

- name: Configuração do kube-controller-manager
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 08-kube-controller-manager
      tags:
        - cluster-kube-controller-manager
        - cluster

- name: Configuração do kube-scheduler
  hosts: managers
  become: true
  gather_facts: false
  roles:
    - role: 09-kube-scheduler
      tags:
        - cluster-kube-scheduler
        - cluster

- name: Configuração do kubelet
  hosts: cluster
  become: true
  gather_facts: false
  roles:
    - role: 10-kubelet
      tags:
        - cluster-kubelet
        - cluster

- name: Configuração do kube-proxy
  hosts: cluster
  become: true
  gather_facts: false
  roles:
    - role: 11-kube-proxy
      tags:
        - cluster-kube-proxy
        - cluster
