# ansible/ops.yml
---
- name: Configurações base para as máquinas clientes
  hosts:
    - clientes
  become: true
  gather_facts: false
  roles:
    - role: infra-sistema
      tags:
        - ops-sistema
        - ops

- name: Instalação das ferramentas de operação do cluster
  hosts:
    - clientes
  become: false
  gather_facts: false
  roles:
    - role: ops-ferramentas
      tags:
        - ops-ferramentas
        - ops

- name: Instalação da Rede com Canal CNI e dependências
  hosts:
    - clientes
  become: false
  gather_facts: false
  when: plugin_cni == 'canal'
  roles:
    - role: addon-kube-proxy
      tags:
        - ops-kube-proxy
        - ops-cni
        - ops
    - role: cni-canal
      tags:
        - ops-cni-canal
        - ops-cni
        - ops
    - role: addon-kubevip
      tags:
        - ops-kubevip
        - ops-cni
        - ops
    - role: addon-traefik
      tags:
        - ops-traefik
        - ops-cni
        - ops
  tags:
    - ops-cni
    - ops

- name: Instalação da Rede com Cilium CNI
  hosts:
    - clientes
  become: false
  gather_facts: false
  when: plugin_cni == 'cilium'
  roles:
    - role: cni-cilium
      tags:
        - ops-cni-cilium
        - ops-cni
        - ops
  tags:
    - ops-cni
    - ops

- name: Implantação dos exemplos de deploys no cluster
  hosts:
    - clientes
  become: false
  gather_facts: false
  roles:
    - role: ops-exemplos
      tags:
        - exemplos
        - ops-exemplos
  tags:
    - exemplos
    - ops-exemplos
