# ansible/100-exemplos/files/vpa/03-vpa-stress-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-stress-deployment
  namespace: exemplos
  labels:
    app: vpa-stress-deployment
    componente: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpa-stress-deployment
  template:
    metadata:
      labels:
        app: vpa-stress-deployment
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      restartPolicy: Always
      containers:
        - name: stress-container
          image: alpine:3.20
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Iniciando loop de sincronização do estresse de VPA Auto..."
              while true; do
                MIN=$(date +%-M)
                REMAINDER=$(( MIN % 10 ))
                if [ "$REMAINDER" -eq 5 ]; then
                  echo "Minuto atual termina em 5 ($MIN). Iniciando estresse de 2 minutos (120s)..."
                  timeout 120s sh -c 'while true; do dd if=/dev/urandom bs=1M count=10 2>/dev/null | sha256sum | sha512sum | sha512sum > /dev/null; done'
                  echo "Estresse de CPU finalizado. Dormindo por 2 minutos para avançar o relógio..."
                  sleep 120
                else
                  sleep 15
                fi
              done
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
