# ansible/13-configuracoes-cluster/tasks/02-flannel.yml
---
- name: Verificar releases instaladas no Helm
  ansible.builtin.command:
    cmd: "helm list -Aq"
  register: helm_releases
  failed_when: false
  changed_when: false

- name: Instalar o Flannel se não estiver instalado
  when: not (helm_releases.stdout | regex_search('^flannel$', multiline=True))
  block:
    - name: Garantir que namespace kube-flannel existe
      ansible.builtin.command:
        cmd: "kubectl create ns kube-flannel"
      changed_when: true

    - name: Aplicar label PodSecurity no namespace kube-flannel
      ansible.builtin.command:
        cmd: "kubectl label ns kube-flannel pod-security.kubernetes.io/enforce=privileged"
      changed_when: true

    - name: Adicionar repositório helm do Flannel
      ansible.builtin.command:
        cmd: "helm repo add flannel https://flannel-io.github.io/flannel/"
      changed_when: true

    - name: Atualizar repositórios helm
      ansible.builtin.command:
        cmd: "helm repo update"
      changed_when: false

    - name: Garantir diretório charts na home do usuário do ansible
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/charts"
        state: directory
        mode: "0755"

    - name: Criar arquivo de configuração Helm para o Flannel
      ansible.builtin.template:
        src: flannel-helm-config.yml.j2
        dest: "/home/{{ ansible_user }}/charts/flannel-helm-config.yml"
        mode: "0644"

    - name: Instalar chart do Flannel
      ansible.builtin.command:
        cmd: >
          helm install flannel flannel/flannel
          --namespace kube-flannel
          --values /home/{{ ansible_user }}/charts/flannel-helm-config.yml
      changed_when: true
