# ansible/13-configuracoes-cluster/tasks/05-ingress.yml
---
- name: Verificar releases instaladas no Helm
  ansible.builtin.command:
    cmd: "helm list -Aq"
  register: helm_releases
  failed_when: false
  changed_when: false

- name: Instalar o Nginx Ingress Controller se não estiver instalado
  when: not (helm_releases.stdout | regex_search('^ingress-nginx$', multiline=True))
  block:
    - name: Adicionar repositório helm do Nginx Ingress Controller
      ansible.builtin.command:
        cmd: "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
      changed_when: true

    - name: Atualizar repositórios helm
      ansible.builtin.command:
        cmd: "helm repo update"
      changed_when: false

    - name: Garantir diretório chartsna home do usuário do ansible
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/charts"
        state: directory
        mode: "0755"

    - name: Criar arquivo de configuração Helm para o Nginx Ingress Controller
      ansible.builtin.template:
        src: ingress-helm-config.yml.j2
        dest: "/home/{{ ansible_user }}/charts/ingress-helm-config.yml"
        mode: "0644"

    - name: Instalar chart do Nginx Ingress Controller
      ansible.builtin.command:
        cmd: >
          helm install ingress-nginx ingress-nginx/ingress-nginx
          --namespace kube-ingress-controller
          --create-namespace
          --values /home/{{ ansible_user }}/charts/ingress-helm-config.yml
      changed_when: true
