# ansible/10-kube-scheduler-pod/tasks/02-pki.yml
---
- name: Criar estrutura de subdiretórios de PKI do kube-scheduler
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  loop:
    - /etc/kubernetes/conf/kube-scheduler/pki/ca
    - /etc/kubernetes/conf/kube-scheduler/pki/kubeconfig

- name: Copiar CA do Kubernetes
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ pki_cas.kubernetes.path_cert }}"
      dest: "/etc/kubernetes/conf/kube-scheduler/pki/ca/{{ pki_cas.kubernetes.path_cert | basename }}"
      mode: "0644"
  loop_control:
    label: "{{ item.dest }}"
  notify: Reiniciar Static Pod do kube-scheduler

- name: Copiar certificados do kube-scheduler (específico do nó)
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ pki_certs.kube_scheduler.path_cert | format(inventory_hostname) }}"
      dest: "/etc/kubernetes/conf/kube-scheduler/pki/kubeconfig/{{ pki_certs.kube_scheduler.path_cert | format(inventory_hostname) | basename }}"
      mode: "0644"
    - src: "{{ pki_certs.kube_scheduler.path_chave | format(inventory_hostname) }}"
      dest: "/etc/kubernetes/conf/kube-scheduler/pki/kubeconfig/{{ pki_certs.kube_scheduler.path_chave | format(inventory_hostname) | basename }}"
      mode: "0640"
  loop_control:
    label: "{{ item.dest }}"
  notify: Reiniciar Static Pod do kube-scheduler
