# ansible/kube_apiserver/tasks/01-instalacao.yml
---
- name: Baixar arquivo de checksum
  ansible.builtin.get_url:
    url: "{{ checksum_url }}"
    dest: "/vagrant/arquivos/tmp/kube-apiserver.sha256"
    mode: "0644"

- name: Ler checksum do arquivo
  ansible.builtin.shell: |
    cat /vagrant/arquivos/tmp/kube-apiserver.sha256 | tr -d '\n'
  register: kube_apiserver_checksum
  changed_when: false

- name: Baixar binário do kube-apiserver para pasta temporária
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "/vagrant/arquivos/tmp/kube-apiserver"
    mode: "0755"
    checksum: "sha256:{{ kube_apiserver_checksum.stdout }}"

- name: Copiar kube-apiserver para pasta final
  ansible.builtin.copy:
    src: "/vagrant/arquivos/tmp/kube-apiserver"
    dest: "/usr/local/bin/kube-apiserver"
    mode: "0755"
    remote_src: yes

- name: Criar arquivos de log
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    owner: etcd
    group: etcd
    mode: "0640"
  loop:
    - /var/log/kubernetes/apiserver.log
    - /var/log/kubernetes/apiserver.err

- name: Configurar logrotate para o kube-apiserver
  ansible.builtin.template:
    src: kube-apiserver.logrotate.j2
    dest: /etc/logrotate.d/kube-apiserver
    mode: '0644'
    owner: root
    group: root