# inventario/hosts.yml
---
all:
  vars:
    ansible_user: vagrant

  children:
    loadbalancers:
      hosts:
        loadbalancer1:
          ansible_host: 172.24.0.21
          fqdn: loadbalancer1.k8sbox.local
          memory: 1024
          cpus: 1

    managers:
      hosts:
        manager1:
          ansible_host: 172.24.0.31
          fqdn: manager1.k8sbox.local
          memory: 2048
          cpus: 2
        manager2:
          ansible_host: 172.24.0.32
          fqdn: manager2.k8sbox.local
          memory: 2048
          cpus: 2
        manager3:
          ansible_host: 172.24.0.33
          fqdn: manager3.k8sbox.local
          memory: 2048
          cpus: 2

    workers:
      hosts:
        worker1:
          ansible_host: 172.24.0.41
          fqdn: worker1.k8sbox.local
          memory: 1024
          cpus: 1
        worker2:
          ansible_host: 172.24.0.42
          fqdn: worker2.k8sbox.local
          memory: 1024
          cpus: 1

    k8s_nodes:
      children:
        managers: {}
        workers: {}

    todos:
      children:
        loadbalancers: {}
        k8s_nodes: {}

    # clientes:
    #   hosts:
    #     kubox:
    #       ansible_host: 172.24.0.254
    #       fqdn: kubox.k8sbox.local
    #       memory: 512
    #       cpus: 1
